name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Build PowerShell Docker image for tests
      run: |
        docker build --platform=linux/amd64 -f tests/Dockerfile -t powershell-image tests/
      continue-on-error: false
    - name: Run tests
      run: pytest -vvs
      env:
        BRIEF_BRIDGE_COMMAND_TIMEOUT: 2.5
        BRIEF_BRIDGE_USE_MOCK_NGROK: true
