name: Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest pytest-bdd
    - name: Run tests
      run: pytest -vvs --ignore=tests/e2e
      env:
        BRIEF_BRIDGE_TEST_TIMEOUT: 2.5
        BRIEF_BRIDGE_USE_MOCK_NGROK: true
